title: Responsible Vibe Coding
description: Best Practices for AI-Assisted Contributions in Open Source
url: "https://rvc-guide.github.io"
baseurl: ""

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

plugins:
  - jekyll-feed
  - jekyll-sitemap

exclude:
  - README.md
  - LICENSE
